# Generated by Django 4.2.29 on 2026-03-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('short_description', models.TextField(verbose_name='Descripción corta')),
                ('long_description', models.TextField(verbose_name='Descripción larga')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('cover_image', models.ImageField(upload_to='books/covers/', verbose_name='Imagen de portada')),
                ('gallery_images', models.JSONField(blank=True, default=list, verbose_name='Imágenes de galería')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['-created_at'],
            },
        ),
    ]
