# Generated by Django 4.2.29 on 2026-03-15 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50, verbose_name='Tipo de evento')),
                ('payment_id', models.CharField(max_length=255, verbose_name='ID de pago')),
                ('status', models.CharField(max_length=50, verbose_name='Estado')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Datos crudos')),
                ('processed', models.BooleanField(default=False, verbose_name='Procesado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='orders.order')),
            ],
            options={
                'verbose_name': 'Evento de Pago',
                'verbose_name_plural': 'Eventos de Pago',
                'ordering': ['-created_at'],
            },
        ),
    ]
